// <auto-generated />
using EmployeeWebService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeWebService.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20200113093104_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("EmployeeWebService.Models.Employee", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("HourlyWage")
                        .HasColumnType("REAL");

                    b.Property<double>("HoursPerMonth")
                        .HasColumnType("REAL");

                    b.HasKey("Name");

                    b.ToTable("employees");
                });
#pragma warning restore 612, 618
        }
    }
}
